env:
  - DOCKER_COMPOSE_VERSION=1.23.2

services:
  - docker

before_install:
  - sudo apt-get update
  - docker --version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - docker --version
  - docker-compose --version
  - ls -lart
  - docker build -t proton_stretch_test:latest .
  - ./test-env-gen.sh
  - ls -lart
  - cat .test-env
  - docker-compose down pg redis proton_test
  - lsof -nti:5432 | xargs kill -9
  - lsof -nti:6379 | xargs kill -9
  - lsof -nti:4000 | xargs kill -9
  - set -a && source .test-env
  - docker-compose up --force-recreate -d pg redis proton_test

script:
  - docker run proton_test -pt yes

after_script:
  - docker-compose down pg redis proton_test
  - docker stop $(docker ps -a -q)
  - docker rm $(docker ps -a -q)
  - lsof -nti:5432 | xargs kill -9
  - lsof -nti:6379 | xargs kill -9
  - lsof -nti:4000 | xargs kill -9
  - rm ./test-env