version: "3"
services:
  pg:
    container_name: proton_postgres
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_TARGET_DB}
    volumes:
      - ${PROTON_POSTGRES_VOLUME_MOUNT}:/var/lib/postgresql/data
    ports:
      - ${PG_TARGET_PORT}:${PG_TARGET_PORT}
  redis:
    container_name: proton_redis
    restart: always
    image: redis
    volumes:
      - ${PROTON_REDIS_VOLUME_MOUNT}:/data
    ports:
      - ${REDIS_TARGET_PORT}:${REDIS_TARGET_PORT}
  proton:
    container_name: proton
    restart: always
    image: proton_stretch
    ports:
      - ${PROTON_TARGET_PORT}:${PROTON_TARGET_PORT}
    expose:
      - ${PROTON_TARGET_PORT}
    volumes:
      - .:/home/PROTON
      - ${PROTON_SQLITE_VOLUME_MOUNT}:/home/PROTON/proton-db
    depends_on:
      - pg
      - redis
    entrypoint: ["./proton.sh"]
  prometheus:
    image: prom/prometheus
    container_name: proton_prometheus
    volumes:
      - "./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml"
    ports:
      - "9090:9090"
    expose:
      - 9090
    depends_on:
      - proton
  grafana:
    image: grafana/grafana
    container_name: proton_grafana
    ports:
      - "3001:3000"
    volumes:
      - "./grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml"
    depends_on:
      - prometheus