version: "3"
services:
  pg:
    container_name: proton_postgres
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_TARGET_DB}
    volumes:
      - ${PROTON_POSTGRES_VOLUME_MOUNT}:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    container_name: proton_redis
    restart: always
    image: redis
    volumes:
      - ${PROTON_REDIS_VOLUME_MOUNT}:/data
    ports:
      - 6379:6379
  proton:
    container_name: proton
    restart: always
    image: proton_stretch
    ports:
      - 3000:3000
    volumes:
      - .:/home/PROTON
    depends_on:
      - pg
      - redis
    entrypoint: ["./proton.sh"]