{
 "title": "Proton Monitor",
 "description": "Proton Monitor",
 "tags": [ "Proton Monitor" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "3s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total requests per minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(http_total_request_total[1m])",
     "legendFormat": "HTTP {{ status }}"
    }
   ]
  },
  {
   "title": "Memory usage - Overall Proton Stack",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{}",
     "legendFormat": "mem - {{instance}}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(request_latency_seconds_count{status=\"200 OK\"}[30s])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_latency_seconds_count{status!=\"200 OK\"}[30s]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "CPU usage - Overall Proton Stack",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{}[30s])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Average response time [30s]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(request_latency_seconds_sum{status=\"200 OK\"}[30s])\n/\nrate(request_latency_seconds_count{status=\"200 OK\"}[30s])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - 0.5",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(request_latency_seconds_bucket{status=\"200 OK\"}[30s]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "process open fds - Overall Proton Stack",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "(process_open_fds{})", "legendFormat": "cpu" }
   ]
  },
  {
   "title": "Requests under 250ms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "increase(request_latency_seconds_bucket{status=\"200 OK\",le=\"0.25\"}[30s]) \n/ ignoring (le) increase(request_latency_seconds_count{status=\"200 OK\"}[30s])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - 0.9",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 10, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(request_latency_seconds_bucket{status=\"200 OK\"}[30s]))",
     "legendFormat": "{{ path }}"
    }
   ]
  }
 ]
}