definitions: {}
info:
  title: PROTON STACK
  version: 1.0.0
parameters: {}
paths:
  /get_tv6_default:
    get:
      description: GET call for  leveraging Ctrl_ of PROTON MIC
      responses:
        200:
          description: <Add description relevant to GET. This will be picked by Swagger
            generator>
          schema: <Schema of Response>
  /post_tv6_default:
    post:
      description: POST call for  leveraging Ctrl_ of PROTON MIC
      responses:
        201:
          description: <Add description relevant to POST. This will be picked by Swagger
            generator>
          schema: <Schema of Response>
  /get_tv6_default_http_concurrency:
    get:
      description: GET call for  leveraging Ctrl_ of PROTON MIC
      responses:
        200:
          description: <Add description relevant to GET. This will be picked by Swagger
            generator>
          schema: <Schema of Response>
swagger: '2.0'
tags: []
